### ISSUE TITLE
o pana e nimi "#toki-pona" tawa lipu ni

### ISSUE THREAD

**Issue by increpare** [stefichjo/toki-pona#94]
jan Tepan o toki!

tenpo ni la sina kepeken nimi #tokipona.  taso kulupu Kitu la pali mute li kepeken nimi #toki-pona (pali lili li kepeken nimi #tokipona).  mi pilin e ni: sina wile kepeken e nimi tu! (nimi #tokipona en nimi #toki-pona).

https://github.com/topics/tokipona
https://github.com/topics/toki-pona

ni la jan ante li ken alasa e lipu sina kepeken pali lili :)

**Comment by stefichjo** [comment]
jan Inkepa o,

pona tawa sina! mi pana e nimi "#toki-pona" tawa lipu ni.
o weka e ike mi ni: mi lukin ala e toki sina. tan ike ni la mi toki sin tawa sina lon tenpo suli ni taso.
